name: CI Pipeline
on: [push, pull_request, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and run tests
        run: ./script/build.bat
      - uses: actions/upload-artifact@v2
        with:
          name: built
          path: .
